import { Zone } from '../types/index';

export const MOCK_ZONES: Zone[] = [
  {
    id: 'zone-01',
    name: '채소1동',
    shortName: '채소1',
    type: 'vegetable',
    lat: 37.4935,
    lng: 127.1185,
    dockDescription: '정문 좌측 A~D 도크, 1번 게이트 진입',
    entryNote: '11톤 이상 서측 게이트 전용',
  },
  {
    id: 'zone-02',
    name: '채소2동',
    shortName: '채소2',
    type: 'vegetable',
    lat: 37.4942,
    lng: 127.1196,
    dockDescription: '2번 게이트 직진 후 우회전, E~H 도크',
  },
  {
    id: 'zone-03',
    name: '과일동',
    shortName: '과일',
    type: 'fruit',
    lat: 37.492,
    lng: 127.12,
    dockDescription: '동측 입구, 1~8번 도크',
    entryNote: '냉장 차량 별도 구역 안내 받을 것',
  },
  {
    id: 'zone-04',
    name: '수산동',
    shortName: '수산',
    type: 'fish',
    lat: 37.491,
    lng: 127.1178,
    dockDescription: '서문 진입 후 좌측, 냉동 하역장',
    entryNote: '11톤 이상 사전 예약 필수',
  },
  {
    id: 'zone-05',
    name: '건어물동',
    shortName: '건어물',
    type: 'dry',
    lat: 37.4916,
    lng: 127.121,
    dockDescription: '남측 소형 게이트, 5톤 이하 권장',
  },
  {
    id: 'zone-06',
    name: '일반동',
    shortName: '일반',
    type: 'general',
    lat: 37.495,
    lng: 127.1174,
    dockDescription: '북문 진입, 서/동측 하역장 구분',
  },
];
