import { WaitReport, Zone } from '@grmap/shared/types';

export const MOCK_ZONES: Zone[] = [
  {
    id: 'zone-01',
    name: '채소1동',
    shortName: '채소1',
    type: 'vegetable',
    lat: 37.4935,
    lng: 127.1185,
    dockDescription: '정문 좌측 A~D 도크, 1번 게이트 진입',
    entryNote: '11톤 이상 서측 게이트 전용',
  },
  {
    id: 'zone-02',
    name: '채소2동',
    shortName: '채소2',
    type: 'vegetable',
    lat: 37.4942,
    lng: 127.1196,
    dockDescription: '2번 게이트 직진 후 우회전, E~H 도크',
  },
  {
    id: 'zone-03',
    name: '과일동',
    shortName: '과일',
    type: 'fruit',
    lat: 37.492,
    lng: 127.12,
    dockDescription: '동측 입구, 1~8번 도크',
    entryNote: '냉장 차량 별도 구역 안내 받을 것',
  },
  {
    id: 'zone-04',
    name: '수산동',
    shortName: '수산',
    type: 'fish',
    lat: 37.491,
    lng: 127.1178,
    dockDescription: '서문 진입 후 좌측, 냉동 하역장',
    entryNote: '11톤 이상 사전 예약 필수',
  },
  {
    id: 'zone-05',
    name: '건어물동',
    shortName: '건어물',
    type: 'dry',
    lat: 37.4916,
    lng: 127.121,
    dockDescription: '남측 소형 게이트, 5톤 이하 권장',
  },
  {
    id: 'zone-06',
    name: '일반동',
    shortName: '일반',
    type: 'general',
    lat: 37.495,
    lng: 127.1174,
    dockDescription: '북문 진입, 서/동측 하역장 구분',
  },
];

export const MOCK_REPORTS: WaitReport[] = [
  {
    id: 'r-001',
    zoneId: 'zone-01',
    waitLevel: 'over60',
    vehicleSize: '11ton_plus',
    message: undefined,
    deviceId: 'mock-device-1',
    platform: 'app',
    status: 'active',
    createdAt: Date.now() - 12 * 60000,
    expiresAt: Date.now() + 33 * 60000,
    upvotes: 0,
  },
  {
    id: 'r-002',
    zoneId: 'zone-03',
    waitLevel: 'none',
    vehicleSize: '5ton',
    message: undefined,
    deviceId: 'mock-device-2',
    platform: 'app',
    status: 'active',
    createdAt: Date.now() - 5 * 60000,
    expiresAt: Date.now() + 40 * 60000,
    upvotes: 0,
  },
  {
    id: 'r-003',
    zoneId: 'zone-04',
    waitLevel: 'under30',
    vehicleSize: '1ton',
    message: undefined,
    deviceId: 'mock-device-3',
    platform: 'app',
    status: 'active',
    createdAt: Date.now() - 20 * 60000,
    expiresAt: Date.now() + 25 * 60000,
    upvotes: 0,
  },
  {
    id: 'r-004',
    zoneId: 'zone-06',
    waitLevel: 'over60',
    vehicleSize: null,
    message: undefined,
    deviceId: 'mock-device-4',
    platform: 'app',
    status: 'active',
    createdAt: Date.now() - 38 * 60000,
    expiresAt: Date.now() + 7 * 60000,
    upvotes: 0,
  },
];

export function buildKakaoNaviDeeplink(lat: number, lng: number): string {
  return `kakaomap://look?p=${lat},${lng}`;
}
